# Generated by Django 4.2.19 on 2025-03-04 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('star', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='star',
            options={'ordering': ['name'], 'verbose_name': 'Знаменитость', 'verbose_name_plural': 'Знаменитости'},
        ),
    ]
