# Generated by Django 5.1.6 on 2025-03-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star', '0005_alter_category_slug_alter_country_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='star',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фотография'),
        ),
    ]
