# Generated by Django 4.2.19 on 2025-03-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star', '0007_alter_star_birth_date_alter_star_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='star',
            name='death_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата смерти'),
        ),
        migrations.AddField(
            model_name='star',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='star',
            name='ruwiki',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на RuWiki'),
        ),
        migrations.AddField(
            model_name='star',
            name='wikipedia',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на Wikipedia'),
        ),
    ]
