# Generated by Django 4.2.19 on 2025-03-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star', '0008_star_death_date_star_rating_star_ruwiki_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='star',
            name='country',
        ),
        migrations.AddField(
            model_name='star',
            name='countries',
            field=models.ManyToManyField(related_name='stars', to='star.country', verbose_name='Связанные страны'),
        ),
    ]
