# Generated by Django 4.2.19 on 2025-04-09 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star', '0010_feedbackmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='name_2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название в родительном падеже'),
        ),
    ]
