# Generated by Django 4.2.19 on 2025-04-14 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('star', '0012_add_performance_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Страна', 'verbose_name_plural': 'Страны'},
        ),
        migrations.RenameIndex(
            model_name='category',
            new_name='star_catego_title_c1a26b_idx',
            old_name='category_title_idx',
        ),
        migrations.RenameIndex(
            model_name='country',
            new_name='star_countr_name_99456c_idx',
            old_name='country_name_idx',
        ),
    ]
